trigger:
- main

strategy:
  matrix:
    linux:
      vmImage: 'ubuntu-latest'
    windows:
      vmImage: 'windows-2022'


pool:
  name: MPool
  demands:
  - ImageOverride -equals $(vmImage)

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'

- script: dotnet build --configuration Release
  displayName: 'Build project'

- script: dotnet test --configuration Release --no-build --verbosity normal
  displayName: 'Run tests'